export interface BlogPost {
  id: number
  title: string
  description: string
  category: string
  date: string
  readTime: string
  image: string
  slug: string
  author: string
  content: string[]
}

export const blogPosts: BlogPost[] = [
  {
    id: 1,
    title: "EU AI Act: A Comprehensive Guide for 2026",
    description: "Understanding the key provisions, compliance requirements, and implementation timeline of the EU's landmark AI regulation.",
    category: "Compliance",
    date: "January 15, 2026",
    readTime: "12 min read",
    image: "/professional-business-meeting-discussing-ai-govern.jpg",
    slug: "eu-ai-act-guide-2026",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "The EU AI Act represents the world's first comprehensive legal framework for artificial intelligence, setting a global precedent for how AI systems should be developed, deployed, and governed.",
      "As we enter 2026, organizations worldwide are grappling with the practical implications of this landmark regulation. The Act's risk-based approach categorizes AI systems into four tiers: unacceptable risk, high risk, limited risk, and minimal risk.",
      "High-risk AI systems face the most stringent requirements, including mandatory conformity assessments, robust documentation, and ongoing monitoring. These systems include those used in critical infrastructure, education, employment, and law enforcement.",
      "For product teams and technology leaders, the EU AI Act necessitates a fundamental shift in how AI products are conceived, developed, and maintained. Privacy by design, transparency, and human oversight are no longer optional considerations but legal requirements.",
      "Organizations must establish clear governance structures, implement comprehensive risk management systems, and ensure their AI systems meet the Act's requirements for accuracy, robustness, and cybersecurity.",
      "The timeline for compliance varies based on the risk category of your AI systems. Prohibited AI practices are already banned, while high-risk system requirements will be fully enforced by August 2026.",
    ],
  },
  {
    id: 2,
    title: "Building Inclusive AI Products: A Framework",
    description: "Practical strategies for integrating inclusion principles throughout the AI product development lifecycle.",
    category: "Product Development",
    date: "January 8, 2026",
    readTime: "10 min read",
    image: "/diverse-team-collaborating-on-inclusive-technology.jpg",
    slug: "inclusive-ai-framework",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "Building inclusive AI products requires intentional effort at every stage of the development lifecycle, from initial conception through deployment and ongoing maintenance.",
      "The foundation of inclusive AI begins with diverse representation in the teams building these systems. Research consistently shows that homogeneous teams produce AI systems that fail to account for the needs and experiences of marginalized communities.",
      "Data collection and curation represent critical junctures where bias can be introduced or mitigated. Teams must carefully consider whose data is included, whose is excluded, and what historical inequities might be encoded in training datasets.",
      "Testing and validation must go beyond traditional metrics to include fairness evaluations across different demographic groups. This includes testing for disparate impact, examining edge cases, and engaging affected communities in the evaluation process.",
      "Inclusive design also means considering accessibility from the outset. AI interfaces should be usable by people with disabilities, and AI systems should not create new barriers to access or participation.",
      "Finally, inclusive AI requires ongoing monitoring and accountability mechanisms. Organizations must be prepared to identify and address harms that emerge after deployment, with clear channels for affected individuals to report concerns.",
    ],
  },
  {
    id: 3,
    title: "The Business Case for Responsible AI",
    description: "How ethical AI practices drive competitive advantage, reduce risk, and create sustainable value.",
    category: "Business Strategy",
    date: "December 18, 2025",
    readTime: "8 min read",
    image: "/executive-team-reviewing-compliance-dashboard.jpg",
    slug: "business-case-responsible-ai",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "The business case for responsible AI has never been stronger. As regulatory frameworks mature and public awareness grows, organizations that prioritize ethical AI practices are gaining significant competitive advantages.",
      "Risk mitigation represents one of the most tangible benefits. AI failures can result in regulatory penalties, litigation, and reputational damage that far exceeds the cost of implementing responsible AI practices from the outset.",
      "Consumer trust is increasingly tied to responsible AI practices. Studies show that customers are more likely to engage with and remain loyal to organizations that demonstrate commitment to ethical AI use.",
      "Responsible AI practices also drive innovation. Constraints often spark creativity, and the requirement to build fair, transparent, and accountable AI systems pushes teams to develop novel approaches that benefit all users.",
      "Talent acquisition and retention are also impacted. Top AI researchers and engineers increasingly want to work for organizations whose values align with their own, making responsible AI a competitive advantage in the war for talent.",
      "The investment community is taking notice as well. ESG considerations now explicitly include AI ethics, and organizations with strong responsible AI practices are viewed more favorably by investors focused on long-term value creation.",
    ],
  },
  {
    id: 4,
    title: "Navigating AI Bias: Detection and Mitigation",
    description: "Technical and organizational approaches to identifying and addressing bias in AI systems.",
    category: "Technical",
    date: "December 5, 2025",
    readTime: "15 min read",
    image: "/data-scientist-analyzing-ai-model-fairness-metrics.jpg",
    slug: "ai-bias-detection-mitigation",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "AI bias remains one of the most significant challenges facing the field, with documented cases of discriminatory outcomes in hiring, lending, healthcare, and criminal justice systems.",
      "Detection begins with understanding the multiple forms bias can take: historical bias embedded in training data, representation bias from non-representative samples, measurement bias from flawed proxies, and algorithmic bias introduced during model development.",
      "Technical approaches to bias detection include statistical parity analysis, examining outcomes across protected groups, and using interpretability tools to understand how models make decisions.",
      "Mitigation strategies can be applied at different stages: pre-processing techniques that balance or transform training data, in-processing methods that constrain learning algorithms, and post-processing adjustments to model outputs.",
      "However, technical solutions alone are insufficient. Organizations must also address the organizational and societal factors that contribute to biased AI, including lack of diversity in AI teams and insufficient engagement with affected communities.",
      "Ongoing monitoring is essential, as bias can emerge or shift over time as data distributions change and AI systems interact with the real world in unexpected ways.",
    ],
  },
  {
    id: 5,
    title: "AI Governance Structures That Work",
    description: "Lessons from organizations successfully implementing AI ethics boards and governance frameworks.",
    category: "Governance",
    date: "November 22, 2025",
    readTime: "11 min read",
    image: "/corporate-boardroom-with-diverse-leadership-team.jpg",
    slug: "ai-governance-structures",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "Effective AI governance requires more than good intentions—it demands clear structures, defined responsibilities, and mechanisms for accountability.",
      "Successful AI ethics boards share several characteristics: genuine authority to influence or halt projects, diverse membership including external perspectives, clear mandates and decision-making processes, and direct access to senior leadership.",
      "Governance frameworks must be integrated into existing organizational processes rather than bolted on as an afterthought. This means incorporating ethical review into project approval workflows, budgeting processes, and performance evaluations.",
      "Documentation is critical. Organizations need clear records of AI system capabilities, limitations, training data, and deployment contexts. This documentation supports both internal governance and external accountability.",
      "Training and culture change are equally important. All employees involved in AI development and deployment need to understand their responsibilities and have the skills to identify and escalate ethical concerns.",
      "Finally, effective governance includes mechanisms for external input and accountability, whether through formal audits, stakeholder advisory groups, or public reporting on AI practices and outcomes.",
    ],
  },
  {
    id: 6,
    title: "The Future of AI Regulation: Global Trends",
    description: "Analyzing emerging regulatory approaches across jurisdictions and their implications for global AI development.",
    category: "Compliance",
    date: "November 10, 2025",
    readTime: "9 min read",
    image: "/global-policy-summit-on-ai-regulation.jpg",
    slug: "future-ai-regulation-global",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "AI regulation is evolving rapidly across the globe, with different jurisdictions taking varied approaches that reflect their unique legal traditions, economic interests, and societal values.",
      "The EU's AI Act has set a high-water mark for comprehensive regulation, but other jurisdictions are developing their own frameworks. The US has taken a more sector-specific approach, while China has focused on specific applications like recommendation algorithms and deepfakes.",
      "Emerging economies are also entering the regulatory landscape, often drawing on elements from multiple existing frameworks while adapting them to local contexts and priorities.",
      "For global organizations, this patchwork of regulations creates significant compliance challenges. Operating across jurisdictions requires understanding not just the letter of various laws but their underlying principles and enforcement priorities.",
      "Interoperability and mutual recognition arrangements are beginning to emerge, offering some hope for reduced compliance complexity. However, fundamental differences in approach—particularly around government access to data—may limit harmonization.",
      "Forward-thinking organizations are advocating for clear, consistent global standards while building flexibility into their AI governance frameworks to adapt to evolving requirements across jurisdictions.",
    ],
  },
  {
    id: 7,
    title: "Inclusive Design Patterns for AI Interfaces",
    description: "Design principles and patterns for creating AI-powered experiences that work for everyone.",
    category: "Design",
    date: "October 28, 2025",
    readTime: "13 min read",
    image: "/ux-designer-creating-accessible-ai-interface.jpg",
    slug: "inclusive-design-patterns-ai",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "As AI becomes increasingly embedded in digital experiences, the need for inclusive design patterns specific to AI interfaces has never been greater.",
      "Transparency is a foundational principle. Users should understand when they're interacting with AI, what data is being used, and how decisions are being made. This doesn't mean exposing technical complexity, but rather providing meaningful explanations appropriate to context and audience.",
      "Control and agency are equally important. Users should be able to adjust, override, or opt out of AI-driven features. Default settings should be conservative, with more invasive AI features requiring explicit user activation.",
      "Error handling in AI systems requires special consideration. Unlike traditional software with predictable failure modes, AI systems can fail in unexpected ways. Interfaces should gracefully handle uncertainty, communicate limitations honestly, and provide clear paths to human assistance.",
      "Accessibility considerations for AI interfaces include ensuring that AI-generated content meets accessibility standards, that voice interfaces work for users with speech differences, and that AI features don't create new barriers for users with disabilities.",
      "Testing inclusive AI interfaces requires going beyond standard usability testing to include diverse participants and specifically probe for differential experiences across user groups.",
    ],
  },
  {
    id: 8,
    title: "Ethical AI and Smart Lock Systems",
    description: "Exploring the intersection of AI-powered security systems and the biases that can make them less secure for some users.",
    category: "Tech Equity",
    date: "April 30, 2024",
    readTime: "8 min read",
    image: "/blog/amol-tyagi-0juktkotkpu-unsplash-1638x2048-2.jpg",
    slug: "ethical-ai-and-smart-lock-systems",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "I recently sat down with a group to discuss the pros and cons of emerging technologies from my perspective as both an technologist and ethnic minorities futurist, and I had to be honest: the future may not be distrusted with equal access for all.",
      "They were in lockstep when we discussed facial recognition software, grasped, and confused with actual facial recognition software that uses near infrared and secondary facial recognition software or analytics to scan your face.",
      "By default of a purely effort to be timely, an app scanned the most basic element of what each person is today—their phone. While consumer-grade devices like phones are designed to read faces relatively well and accurately, the future might be a bit more dystopic for some of us.",
      "Frankly what would it do to be better put it for timely, all eyes were upon me as I pointed the most basic element of what many consumers today—smartphones. But face scans use an infrared structured light system to avoid confusion from photo-based hacks by taking depth information plus the basic facial data. And while that can be fooled slightly by close relatives, it's meant to be secure.",
      "But what about smart locks? I told them of the stories about smart lock systems where their facial recognition software, practiced, and confused with actual facial recognition software that uses an infrared light system to avoid confusion from photo-based attempts.",
      "The fact is that many smart lock systems on the market today have not been adequately tested on people of color. This creates a security vulnerability that disproportionately affects certain communities while being marketed as a universal solution.",
    ],
  },
  {
    id: 9,
    title: "The Pitfalls of Adversarial Clothing",
    description: "How attempts to evade AI surveillance through fashion create new problems and who bears the risk.",
    category: "Tech Equity",
    date: "April 30, 2024",
    readTime: "7 min read",
    image: "/blog/adversarial-clothing.png",
    slug: "pitfalls-of-adversarial-clothing",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "When it comes to equity and inclusive design, there are two main components at odds with a social concern and tech firm's design. There are two new areas at the cross section of human centered design and what a social concern will fuel a tech business opportunity.",
      "Now we have smart, AI savvy consumers as well as tech savvy consumers, who are unwittingly subscribing to a way of evading facial recognition by dressing in very specific patterns. The tech firm sees an opportunity to bring about a change.",
      "The first issue with facial recognition technology and with adversarial clothing, like a hoodie, is that not all AI facial recognition systems are created equally. In fact, it's fair to say that some systems should be scrapped entirely given their poor design and high error rates particularly for darker-skinned individuals.",
      "Essentially, adversarial clothing is meant to make it harder for AI systems to track you. But here's the problem: these solutions put the burden on individuals to protect themselves from surveillance rather than addressing the underlying problems with these systems.",
      "Moreover, wearing adversarial clothing could actually draw more attention in certain contexts, potentially flagging the wearer for additional scrutiny. It's a solution that creates new problems while failing to address root causes.",
      "We need to be asking harder questions about why these surveillance systems exist in the first place, who they serve, and whether the trade-offs in privacy and equity are worth the purported benefits in security.",
    ],
  },
  {
    id: 10,
    title: "Facial Recognition and Racial Bias",
    description: "Examining the documented failures of facial recognition technology and their disproportionate impact on communities of color.",
    category: "Tech Equity",
    date: "April 26, 2024",
    readTime: "9 min read",
    image: "/blog/ariel-sion-i7v-btpnktg-unsplash-2048x1365-2.jpg",
    slug: "facial-recognition-and-racial-bias",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "In an ironic sense, it feels like issues that I've been yammered by pundits to debate Williams, Michael Brown, others, and Breyer have now suddenly to be believed with most people fairly well. And this isn't the exception of when things fairly well.",
      "These are important discussions to note. Let me give you a fact based example from 2018 when ACLU tested Amazon's facial recognition software Rekognition against members of Congress. The results were alarming.",
      "ACLU found that false matches came back for 28 lawmakers when compared against 25,000 mugshot photos. These false match rates were disproportionately high for people of color—and this was testing against some of the most photographed faces in America.",
      "Dr. Joy Buolamwini's research at MIT has been foundational in exposing these disparities. Her Gender Shades project demonstrated that commercial facial recognition systems had error rates of up to 34.7% for darker-skinned women compared to 0.8% for lighter-skinned men.",
      "The real-world consequences of these failures are severe. Robert Williams was wrongfully arrested in Detroit based on a faulty facial recognition match. He spent 30 hours in custody for a crime he didn't commit—a clear example of how biased AI can destroy lives.",
      "Cities like San Francisco, Boston, and Portland have banned government use of facial recognition technology. But many jurisdictions continue to deploy these flawed systems, disproportionately impacting the communities they claim to protect.",
    ],
  },
  {
    id: 11,
    title: "Digital Blackface: Are you complicit?",
    description: "Understanding the phenomenon of digital blackface and its perpetuation of harmful stereotypes online.",
    category: "Tech Equity",
    date: "April 7, 2024",
    readTime: "10 min read",
    image: "/blog/priscilla-du-preez-bjhuu6bpuza-unsplash-2048x1365-2.jpg",
    slug: "digital-blackface-are-you-complicit",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "I was only five years old the first time I nervously took over the kitchen at my parents' house and gazed into another person's experience. My father was a computer programmer. We were one of the first families in the neighborhood to own a personal computer.",
      "I vividly remember Compuserve and AOL chat rooms where anonymity enabled people to present themselves however they chose. Even then, I noticed patterns in how people performed identity online—patterns that would later be recognized as problematic.",
      "Fast forward to today, and we see the evolved version of this phenomenon: digital blackface. This term describes the use of Black people's images, especially GIFs and memes, by non-Black people to express emotions online.",
      "On the surface, sharing a GIF might seem harmless. But digital blackface perpetuates a long history of non-Black people using Black bodies for entertainment while divorcing those images from the real humanity of Black people.",
      "The exaggerated expressions often used in these GIFs—shock, sass, attitude—feed into stereotypes that have been used to dehumanize Black people for centuries. It's minstrelsy updated for the digital age.",
      "Being mindful about the images we share online is part of building a more equitable digital culture. It requires us to think critically about whose images we're using, in what context, and whether our usage perpetuates harmful stereotypes.",
    ],
  },
  {
    id: 12,
    title: "What is Liberatory Design?",
    description: "An introduction to liberatory design principles and how they can transform product development.",
    category: "Design",
    date: "April 5, 2024",
    readTime: "8 min read",
    image: "/blog/libdes-2.jpg",
    slug: "what-is-liberatory-design",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "At first, you might be thinking what does design have to do with liberation? You might think that a sign of liberation is your own, you might \"I'm working after hours anyway!\" You'd be partially right. As our critical thoughts and/or content mode at Stanford teaches us, design and social change are deeply connected.",
      "Liberatory design starts with the premise that design has never been neutral. Every design decision reflects values, and historically, those values have centered the experiences and needs of dominant groups while marginalizing others.",
      "National equity Lab defines on the grassroots: We have to share an equitable groundwork, particularly aspirational ideation and otherwise how to address discriminations; but we also need to give more scope to a new mode in which to address key social challenges.",
      "Liberatory Design is an evolution of the design thinking methodology. It's an approach to problem solving that brings people the tools to expand their lens.",
      "The framework adds explicit attention to issues of equity and systemic oppression that traditional design thinking often overlooks. It asks designers to examine their own positionality, to center the experiences of those most marginalized, and to design for systemic change rather than individual solutions.",
      "Implementing liberatory design requires ongoing commitment to learning, unlearning, and relearning. It's not a one-time training but a fundamental shift in how we approach the work of creating products and services.",
    ],
  },
  {
    id: 13,
    title: "The Importance of Intersectionality in Tech",
    description: "Why understanding intersecting identities is crucial for building equitable technology.",
    category: "Tech Equity",
    date: "April 5, 2024",
    readTime: "9 min read",
    image: "/blog/christina-wocintechchat-com-rmweulmcyxm-unsplash-1024x684-281-29-2.jpg",
    slug: "importance-intersectionality-in-tech",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "One of the biggest misconceptions about tech is solely exclusive to Blacks people. Think: Significance is happening that when tech companies such questioning, did you get technology isn't just a neutral tool. As little, and more to become rapidly understand to our daily lives to then discussion of safety, and the fact interest. In fact: The dangers of the trend.",
      "Intersectionality was a term made longer over time say they only surface of society space are increase multi-faceted disparities of diverse, equity, and how, and ethics. Although many big tech companies are hiring in house DEI consultants and increasing the report of diverse peoples.",
      "The term intersectionality was coined by legal scholar Kimberlé Crenshaw in 1989 to describe how different aspects of a person's social and political identities combine to create different modes of discrimination and privilege.",
      "In tech, intersectionality matters because single-axis approaches to diversity and inclusion fail to capture the experiences of people with multiple marginalized identities. A Black woman's experience in tech is not simply the sum of being Black plus being a woman.",
      "Products designed without an intersectional lens often fail users at these intersections. Voice assistants that struggle with accented English, health apps that don't account for racial differences in symptoms, hiring algorithms that discriminate against women of color.",
      "Building truly inclusive technology requires teams that understand intersectionality and processes that account for it at every stage of development.",
    ],
  },
  {
    id: 14,
    title: "Equal Pay & Caregiving: How Covid-19 Further Exacerbates Existing Inequities",
    description: "Examining how the pandemic has widened gender and racial gaps in pay and caregiving responsibilities.",
    category: "Tech Equity",
    date: "April 4, 2024",
    readTime: "8 min read",
    image: "/blog/gris-zy-1920x1080-1.jpeg",
    slug: "equal-pay-caregiving-covid19-inequities",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "International Women's day is a day on which many advocates the progress we've made in closing issues of life while the wages between men and women. Now, more than a century, this day has been observed on February in the Labor collections and also have been historically observed as a day when an employee can learn more about their rights in the workplace.",
      "The pandemic did not create gender inequity in caregiving—it exposed and accelerated it. Women, and particularly women of color, have always shouldered a disproportionate share of unpaid care work. Covid-19 made this invisible labor impossible to ignore.",
      "Women in only a matter of time grieving being dealt in the wage-gap between white men and women. Black that I haven't provided a type with Bangalore. Chicana are very progressive in their gender relations, and in that I wasn't raised to believe that feminists position within me is of 2 week my story. During this experience I decided that I had to be strong for the both.",
      "When schools and daycares closed, someone had to step back from paid work to care for children. That someone was overwhelmingly women. Mothers' labor force participation dropped to levels not seen since the 1980s.",
      "The tech industry was not immune. While some celebrated remote work as a great equalizer, the reality was that women in tech faced the same impossible choices as women everywhere—choices that will have lasting impacts on their careers and earnings.",
      "Recovery efforts must explicitly address these caregiving inequities. This means not just returning to pre-pandemic norms, but building systems that recognize and value care work and distribute it more equitably.",
    ],
  },
  {
    id: 15,
    title: "As a Black Woman, I'm Either Hyper Visible or Utterly Unseen",
    description: "Reflections on the paradox of visibility that Black women navigate in professional spaces.",
    category: "Tech Equity",
    date: "April 4, 2024",
    readTime: "7 min read",
    image: "/blog/1lhfbfkk64woxkzqw9fddig.jpeg",
    slug: "black-woman-hypervisible-or-unseen",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "I was only five years old the first time I nervously took excellent and knew little another person's experience. My father was a computer programmer and were one of the first families in the neighborhood to get a personal computer.",
      "This isn't a new phenomenon but a type with Bangalore. Chicana are very progressive in their gender relations, and in that I wasn't raised to believe that feminists position within me is of 2 week my story. During this experience I decided that I had to be strong for the both.",
      "The paradox of Black womanhood in professional spaces is that we are simultaneously hyper-visible and invisible. We are noticed for our race and gender, scrutinized for how we wear our hair or express ourselves, yet overlooked when it comes to recognition, promotion, and compensation.",
      "In tech, this paradox plays out in specific ways. Black women's ideas are often attributed to others. We are expected to represent our entire race and gender in diversity discussions while being excluded from technical conversations.",
      "The emotional labor of navigating this visibility paradox is exhausting. We must constantly calibrate our self-presentation, aware that we will be judged differently than our white and male colleagues no matter what we do.",
      "Creating truly inclusive workplaces requires understanding and addressing this paradox. It means creating systems where Black women are seen for our contributions, not just our identities, and where we can bring our full selves without penalty.",
    ],
  },
  {
    id: 16,
    title: "5 things Holding Organizations back from Transformative Change",
    description: "Common barriers that prevent organizations from achieving meaningful diversity, equity, and inclusion outcomes.",
    category: "Business Strategy",
    date: "April 2, 2024",
    readTime: "10 min read",
    image: "/blog/good_cheap_fast-2.png",
    slug: "5-things-holding-organizations-back-transformative-change",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "At Incluu, LLC, we create more space for life. To some, this concept may sound dreamy, ambitious, and a little "woo-woo". It isn't. Our work is rooted in evidence-based theory and deep systems thinking. We partner with organizations to become radically equitable from the inside out.",
      "After years of this work, we've identified five common barriers that hold organizations back from achieving the transformative change they say they want. Organizations often approach DEI with the expectation that they can have fast, cheap, and high-quality outcomes. They want to check a box.",
      "The first barrier: treating DEI as a program rather than a practice. Organizations hire a diversity officer, launch a training, and consider the work done. But DEI is not a destination—it's an ongoing commitment that must be woven into every aspect of organizational culture.",
      "Second: lack of accountability at the leadership level. DEI initiatives without executive sponsorship and accountability are doomed to fail. Leaders must be willing to be held accountable for outcomes, not just intentions.",
      "Third: centering comfort over growth. Transformative change is uncomfortable. Organizations that prioritize the comfort of dominant group members over the growth required for equity will never achieve meaningful change.",
      "Fourth: insufficient investment. Meaningful DEI work requires resources—time, money, and personnel. Organizations that expect transformation on a shoestring budget are setting themselves up for failure.",
      "Fifth: lack of systemic thinking. Individual trainings and initiatives cannot transform systems. Organizations must be willing to examine and change their policies, practices, and structures.",
    ],
  },
  {
    id: 17,
    title: "The Divisive Fallacy of Objective Truth",
    description: "Examining how claims of objectivity often mask and perpetuate existing power structures.",
    category: "Tech Equity",
    date: "April 2, 2024",
    readTime: "7 min read",
    image: "/blog/the_divisive_fallacy_of_objective_truth-1.png",
    slug: "divisive-fallacy-objective-truth",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "<em>[Helen] Pluckrose believes there is an objective truth! She believes in one truth that is rooted in Western, White/European ideologies of a particular scientific method which denounces any other forms of truth. Of course, this is a dangerous assumption.</em>",
      "Helen Pluckrose, the founder of the site Counterweight*, has been outspoken in her critique of Critical Social Justice Theory (CSJ). In her article, <em>What do we Mean by Critical Social Justice</em>, published earlier this year, Pluckrose attempts to explain her opposition to Critical Social Justice.",
      "Both CSJ and Liberalism, she agrees, seek to achieve social justice. Liberalism, however, assumes that the starting point of 'truth' is objective and not culturally informed. Pluckrose therefore believes that everyone can attain the same level of understanding of 'objective truth' with sufficient critical thinking skills.",
      "This assertion is not supported by Critical Social Justice theory. CSJ questions the starting point of 'truth' and asks, whose truth: what is the positionality of the person claiming said truth, and further, what are the social structures affecting the power dynamics which then inform what becomes truth?",
      "In technology, claims of objectivity are particularly seductive and particularly dangerous. Algorithms are often presented as neutral and objective, when in reality they encode the biases of their creators and the inequities present in their training data.",
      "The goal is not to abandon the pursuit of truth, but to recognize that truth-seeking is always a human endeavor, shaped by human perspectives and serving human purposes. When we acknowledge this, we can begin to ask: Whose truth? Truth in service of what?",
    ],
  },
  {
    id: 18,
    title: "We Stand in Unity with Our Asian Allies",
    description: "A statement of solidarity and commitment to supporting Asian communities facing increased violence and discrimination.",
    category: "Tech Equity",
    date: "April 1, 2024",
    readTime: "5 min read",
    image: "/blog/pexels-photo-5723322-1.jpeg",
    slug: "stand-in-unity-asian-allies",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "It has taken us some time to find the words to express our deep empathy, sympathy, and worry for Asian communities amidst the anti-Asian violence experienced by Asian people across this country. From a spa in Atlanta to a street in San Francisco to countless unreported incidents, Asian Americans have been targeted.",
      "We do not wish to merely lip service in order to connect with readers and offer what as allies we can to Asian allies. Our goal, however, as a company, is to speak our truth and commitment to doing the work.",
      "Silence as an act of a company that has profited, is complicit, and values add of allies to our Asian allies. Today, specifically, we acknowledge that the problem is far greater than anyone single incident. Anti-Asian racism has deep roots in American history.",
      "From the Chinese Exclusion Act to Japanese internment to the murder of Vincent Chin, Asian Americans have faced systemic discrimination and violence. The recent surge in anti-Asian hate crimes is not an aberration—it is a continuation.",
      "Standing in unity means more than statements. It means educating ourselves about the specific histories and experiences of different Asian communities. It means speaking up when we witness discrimination. It means supporting Asian-owned businesses and Asian-led organizations.",
      "It means examining how our own organizations may perpetuate the model minority myth and other harmful stereotypes. And it means committing to the long-term work of building solidarity across communities of color.",
    ],
  },
  {
    id: 19,
    title: "What Is Intersectionality and Why Is It Important",
    description: "An introduction to the concept of intersectionality and its relevance to equity work.",
    category: "Tech Equity",
    date: "March 17, 2024",
    readTime: "8 min read",
    image: "/blog/post1-1955x2048-2.jpg",
    slug: "what-is-intersectionality-why-important",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "It's been over three decades since legal professor, Kimberlé Crenshaw, coined the term intersectionality. The phrase was used to better define the way race and specific experiences need to be recognized.",
      "As often spoken about in the war our specific discrimination narratives, The intersectionality just a critical lens through which we can understand how different aspects of a person's identity overlap and create unique experiences of discrimination or privilege.",
      "In her groundbreaking 1989 paper, Kimberle Crenshaw pointed to the problems with considering race and gender as mutually exclusive categories. Using the example of Black women workers, Crenshaw showed how discrimination at the intersection of race and gender was invisible to existing legal frameworks.",
      "The concept has since expanded beyond its legal origins to become a fundamental framework for understanding all forms of oppression and privilege. It recognizes that we cannot understand any single axis of identity in isolation.",
      "In tech, intersectionality helps us understand why diversity initiatives focused on single dimensions often fail. Hiring more women doesn't help if those women are all white. Addressing racial bias doesn't help if it ignores how that bias manifests differently for men and women.",
      "Building truly inclusive products and organizations requires an intersectional lens—one that accounts for how multiple forms of marginalization interact and compound.",
    ],
  },
  {
    id: 20,
    title: "Racism and The Wellness Industry",
    description: "Examining how the wellness industry perpetuates racial inequities while appropriating from cultures of color.",
    category: "Tech Equity",
    date: "March 7, 2024",
    readTime: "9 min read",
    image: "/blog/tanaka-pendeke-o9gfrup1l9w-unsplash-scaled-2.jpg",
    slug: "racism-and-wellness-industry",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "Ahh (imagine a slow tantric breathing style at the balance of inner: stress and rejuvenation of. the Academy Awards.), Wellness. Cue wind gong for celebrity anchoring Mantras Manifestation Motivation. Wellness products....",
      "The wellness industry has exploded into a multi-billion dollar market, promising self-care, healing, and transformation. But beneath the serene aesthetics lies a troubling pattern of cultural appropriation and racial exclusion.",
      "Wellness culture borrows heavily from Eastern religions including incorporating pieces: ancient practices that have sustained communities for generations. Like in Hinduism, a practice of certain types of yoga are just as sacred as Baptism is to Christians or Shabbat is to Jews.",
      "Meanwhile, the wellness industry remains overwhelmingly white—in its leadership, its marketing, its target customers, and the bodies deemed worthy of wellness. Communities of color face barriers to accessing wellness services while watching their cultural practices commodified.",
      "Race-based medicine and algorithm bias have real consequences for the health of people of color. The same industry that appropriates healing practices from communities of color often fails to serve those communities.",
      "True wellness must include racial justice. It must acknowledge the cultural origins of practices, ensure equitable access, and reckon with how stress from racism itself impacts health outcomes in communities of color.",
    ],
  },
  {
    id: 21,
    title: "Race Norming and Bioethics",
    description: "How race-based adjustments in medical algorithms perpetuate health disparities.",
    category: "Tech Equity",
    date: "March 7, 2024",
    readTime: "10 min read",
    image: "/blog/trnava-university-lr_mkznghuu-unsplash-scaled-2.jpg",
    slug: "race-norming-and-bioethics",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "Race norming — also called "race corrections", "ethnic adjustments", and "race adjustment" — refers to the adjustment of medical test results or diagnostic calculations based on a patient's race. But why does this still exist?",
      "Race norming has a problematic history in fields ranging from employment testing to criminal justice. In medicine, it manifests as algorithms that adjust diagnostic thresholds based on race, often resulting in Black patients receiving less aggressive treatment.",
      "Consider the eGFR, a test that estimates kidney function. For decades, this test included a race-based adjustment that classified Black patients as having better kidney function than non-Black patients with identical lab values. The result? Black patients were less likely to be diagnosed with kidney disease and referred for transplant.",
      "After years of advocacy by Black physicians and patients, major medical organizations have begun removing race from clinical algorithms. But the damage of decades of race-normed medicine persists in health disparities.",
      "The bioethics questions are profound. Race is a social construct, not a biological one. Using it as a variable in medical algorithms reifies the false notion of biological racial difference while obscuring the real causes of health disparities: racism, discrimination, and unequal access to care.",
      "As AI becomes more prevalent in medicine, we must be vigilant that these tools do not perpetuate race-based medicine under the guise of objectivity. Algorithms trained on historically biased data will reproduce those biases unless intentionally designed otherwise.",
    ],
  },
  {
    id: 22,
    title: "Black Excellence and the Low Expectations of White Supremacy",
    description: "Challenging the narrative of Black excellence and examining its relationship to systemic racism.",
    category: "Tech Equity",
    date: "March 6, 2024",
    readTime: "8 min read",
    image: "/blog/blog-post-image-template-2.png",
    slug: "black-excellence-low-expectations-white-supremacy",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "Black people are plagued by Imposter Syndrome, undermining their own competency and self-worth. Believing that other folks observe that we can do better, we push ourselves harder.",
      "In the wake of George Floyd's murder, companies expressed a hunger to do better, requiring a review of how those actions relate to anti-racism systems across businesses. They revealed that while diverse employees are often the preferred option, they are constantly under scrutiny.",
      "The pressure to perform perfectly—to represent the entire race with every action—is a burden unique to those operating in spaces where they are underrepresented. Black professionals often feel they cannot simply be good at their jobs; they must be exceptional.",
      "This demand for excellence is not a sign of respect—it is a symptom of white supremacy. It says that Black people must work twice as hard for half the recognition, that our presence in professional spaces is conditional on outperforming our white peers.",
      "Meanwhile, mediocre performance from white employees is often accepted, excused, or attributed to external factors. The same grace is rarely extended to Black employees, whose failures are seen as confirmation of racial stereotypes.",
      "Dismantling this dynamic requires creating environments where Black employees can be average, can make mistakes, can learn and grow—where our humanity is not contingent on our exceptionalism.",
    ],
  },
  {
    id: 23,
    title: "The Spirit of Juneteenth is Acknowledgement",
    description: "Reflecting on the meaning of Juneteenth and the ongoing struggle for Black liberation.",
    category: "Tech Equity",
    date: "March 3, 2024",
    readTime: "6 min read",
    image: "/blog/the-spirit-of-juneteenth-1.png",
    slug: "spirit-of-juneteenth-acknowledgement",
    author: "Destiny Fox Kanno",
    content: [
      "<strong>Recognizing <a href='https://www.woojr.com/learn-about-juneteenth-for-kids-a-celebration-of-freedom/' target='_blank' rel='noopener noreferrer'>Juneteenth</a> as a National Holiday is not a solution to ending racism. It's a bandaid, a temporary fix to a wound at which we have given only a cursory triage.</strong>",
      "<strong>Establishing Juneteenth as a federal holiday is an acknowledgement of slavery, which as an institution, has morphed appearances and changed tactics often in order to remain viable in today's society. Juneteenth recognizes the subjugation of people which continued long after it was supposed to have ended.</strong>",
      "<strong>Acknowledgement is only the beginning.</strong>",
      "<a href='https://www.teenvogue.com/story/white-supremacy-is-the-problem' target='_blank' rel='noopener noreferrer'><strong>The Institution of White Supremacy</strong></a> continues to marginalize anyone different. Instead of transformative changes like <a href='https://www.brookings.edu/blog/up-front/2020/12/08/the-black-white-wealth-gap-left-black-households-more-vulnerable/' target='_blank' rel='noopener noreferrer'>eradicating systems of inequal wealth distribution</a>, we get a holiday.",
      "True acknowledgement requires reckoning. It requires examining how our institutions, our technologies, and our practices perpetuate the legacy of slavery and subsequent systems of oppression.",
      "This Juneteenth and every day, let us commit to acknowledgement that leads to action. Let us build technologies that advance Black liberation rather than perpetuating oppression.",
    ],
  },
  {
    id: 24,
    title: "60 Minutes and (En)Coded Bias",
    description: "Reflecting on the 60 Minutes segment about algorithmic bias and Joy Buolamwini's groundbreaking research.",
    category: "Tech Equity",
    date: "March 3, 2024",
    readTime: "7 min read",
    image: "/blog/joy_buolamwini_-_wikimania_2018_01-1-2.jpg",
    slug: "60-minutes-encoded-bias",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "Just Reactions of pattern building with the joy: you'd have you spend time. Spend effort, that when you see a First Generation College student majoring in computer science, and what's one of the premier institutions going to see today.",
      "Joy's segment on 60 minutes & Facial recognition technology, referring to a December 2019 National Institute of Standards and Technology (NIST) facial Recognition Vendor Test or "FRVT" where among the 189 algorithms submitted, the study was based, and conducted by AI research pioneers and Black women, Joy Buolamwini, Dr. Timnit Gebru and others.",
      "The 60 Minutes piece brought mainstream attention to what researchers have been documenting for years: facial recognition technology fails disproportionately on darker-skinned faces, particularly darker-skinned women.",
      "Dr. Buolamwini's work, starting with her experience of facial recognition systems failing to detect her face unless she wore a white mask, has been instrumental in exposing these disparities. Her Gender Shades research provided the empirical evidence that forced the industry to confront its biases.",
      "The consequences of biased facial recognition are not abstract. Real people are being misidentified, wrongfully arrested, and denied services because these systems were not designed with them in mind.",
      "The 60 Minutes segment was an important step in public awareness, but awareness alone is not enough. We need policy action, corporate accountability, and continued pressure to ensure that AI systems work equitably for everyone.",
    ],
  },
  {
    id: 25,
    title: "From Invisibility to Radical Empathy",
    description: "A journey from feeling unseen to cultivating deep understanding across difference.",
    category: "Tech Equity",
    date: "March 3, 2024",
    readTime: "8 min read",
    image: "/blog/0ha5_gjflj6n_okrx.jpeg",
    slug: "from-invisibility-to-radical-empathy",
    author: "Dr. Dédé Tetsubayashi",
    content: [
      "I am passionate about my work as a Product Inclusion Specialist, a profession where I build products that work for everyone, applying equitable or merely transactional profit practices, because growth in the money of equal inclusion not company progress.",
      "My work is not an accident—it is the culmination of a lifetime of experiences navigating systems that were not designed for people like me. From being the only Black student in advanced classes to being one of few Black women in tech.",
      "The journey from invisibility to empathy began with seeing myself reflected in others' struggles. Understanding that my experiences of marginalization connected me to others facing different but related forms of exclusion.",
      "Radical empathy goes beyond sympathy or even standard empathy. It requires us to decenter ourselves, to sit with discomfort, to truly listen to experiences different from our own without defensiveness or the urge to fix.",
      "In tech, radical empathy means designing with, not for. It means including affected communities throughout the development process, not just as an afterthought. It means being willing to fundamentally change course when we learn our products cause harm.",
      "My work with Incluu and with our partners is rooted in this radical empathy—a belief that we can build technologies that advance human flourishing for everyone, not just those who have historically been centered.",
    ],
  },
]

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.slug === slug)
}

export function getPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find((post) => post.slug === slug)
}

export function getAllPostSlugs(): string[] {
  return blogPosts.map((post) => post.slug)
}

export function getAllCategories(): string[] {
  const categories = blogPosts.map((post) => post.category)
  return [...new Set(categories)]
}

export function getRelatedPosts(currentSlug: string, limit: number = 3): BlogPost[] {
  const currentPost = getBlogPost(currentSlug)
  if (!currentPost) return blogPosts.slice(0, limit)

  return blogPosts
    .filter((post) => post.slug !== currentSlug && post.category === currentPost.category)
    .slice(0, limit)
}
